# Computer Vision

* Create dataset
* make folder train and test with cat and dog classes

In [1]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

2022-12-09 00:05:41.814689: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-09 00:05:41.987694: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-12-09 00:05:41.987719: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-12-09 00:05:42.782291: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2022-

In [2]:
import numpy as np

## Step2: Conver each class image into numpy tensor

In [3]:
train_data_gen = ImageDataGenerator(rescale=1.0/255)

In [4]:
train_data = train_data_gen.flow_from_directory(
    "./data/train/",
    target_size=(60,60),
    batch_size=1,
    class_mode='binary'
)

Found 8 images belonging to 2 classes.


In [5]:
print(train_data.class_indices)
print(train_data.class_mode)
print(train_data.classes)


{'cat': 0, 'dog': 1}
binary
[0 0 0 0 1 1 1 1]


# now create network

In [6]:
150*150*3

67500

In [7]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam, SGD

In [8]:
model = Sequential()
model.add(Flatten())
model.add(Dense(5000, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

2022-12-09 00:05:45.709375: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-12-09 00:05:45.709645: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-12-09 00:05:45.710112: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2022-12-09 00:05:45.710540: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2022-12-09 00:05:45.710607: W tensorflow/c

In [9]:
model.compile(loss='binary_crossentropy',
             optimizer='adam',
             metrics=['acc'])

In [10]:
hist = model.fit(train_data,epochs=10)

2022-12-09 00:05:45.835171: W tensorflow/tsl/framework/cpu_allocator_impl.cc:82] Allocation of 216000000 exceeds 10% of free system memory.
2022-12-09 00:05:45.911120: W tensorflow/tsl/framework/cpu_allocator_impl.cc:82] Allocation of 216000000 exceeds 10% of free system memory.
2022-12-09 00:05:45.948384: W tensorflow/tsl/framework/cpu_allocator_impl.cc:82] Allocation of 216000000 exceeds 10% of free system memory.


Epoch 1/10


2022-12-09 00:05:46.252302: W tensorflow/tsl/framework/cpu_allocator_impl.cc:82] Allocation of 216000000 exceeds 10% of free system memory.
2022-12-09 00:05:46.267154: W tensorflow/tsl/framework/cpu_allocator_impl.cc:82] Allocation of 216000000 exceeds 10% of free system memory.


8/8 [==============================] - 4s 476ms/step - loss: 55.8450 - acc: 0.5000
Epoch 2/10
8/8 [==============================] - 4s 474ms/step - loss: 44.7432 - acc: 0.3750
Epoch 3/10
8/8 [==============================] - 4s 458ms/step - loss: 17.3041 - acc: 0.7500
Epoch 4/10
8/8 [==============================] - 4s 459ms/step - loss: 35.5056 - acc: 0.6250
Epoch 5/10
8/8 [==============================] - 4s 453ms/step - loss: 12.3513 - acc: 0.5000
Epoch 6/10
8/8 [==============================] - 4s 445ms/step - loss: 14.5887 - acc: 0.7500
Epoch 7/10
8/8 [==============================] - 4s 468ms/step - loss: 1.5935e-09 - acc: 1.0000
Epoch 8/10
8/8 [==============================] - 4s 463ms/step - loss: 8.1169e-06 - acc: 1.0000
Epoch 9/10
8/8 [==============================] - 4s 472ms/step - loss: 3.2669e-04 - acc: 1.0000
Epoch 10/10
8/8 [==============================] - 4s 462ms/step - loss: 0.0043 - acc: 1.0000


# Testing

In [11]:
test_data = train_data_gen.flow_from_directory(
    "./data/test/",
    target_size=(60,60),
    batch_size=1,
    class_mode='binary'
)

Found 2 images belonging to 2 classes.


In [12]:
Y = model.predict(test_data)
Y

2/2 [==============================] - 0s 16ms/step


array([[0.0000000e+00],
       [1.3622575e-07]], dtype=float32)

In [13]:
np.where(Y>0, "Dog","Cat")

array([['Cat'],
       ['Dog']], dtype='<U3')

# predict on image 

In [14]:
from tensorflow.keras.preprocessing import image
import numpy as np
img = image.load_img("data/train/dog/2.jpeg", target_size=(60,60))
x= image.img_to_array(img)/255
x = x.reshape(1,-1)
model.predict(x)

1/1 [==============================] - 0s 69ms/step


array([[1.]], dtype=float32)

In [15]:
from tensorflow.keras.preprocessing import image
import numpy as np
img = image.load_img("data/train/cat/2.jpeg", target_size=(60,60))
x= image.img_to_array(img)/255
x = x.reshape(1,-1)
model.predict(x)>0

1/1 [==============================] - 0s 31ms/step


array([[False]])